# Generated by Django 4.2.3 on 2023-07-15 18:01

from django.db import migrations



def populate_priority(apps, schemaeditor):
    entries = {
        "low": "low",
        "medium": "medium",
        "high": "high"
    }
    Priority= apps.get_model("issues", "Priority")
    for name, desc in entries.items():
        priority_obj = Priority(name=name, description=desc)
        priority_obj.save()

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "to do",
        "in progress": "in progress",
        "done": "done"
    }
    Status= apps.get_model("issues", "Status")
    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()




class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority),

    ]
