# Generated by Django 4.2.3 on 2023-07-15 18:01

from django.db import migrations


def populate_teams(apps, schemaeditor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team",
        "delta": "The D team"
}
    Team = apps.get_model("accounts", "Team")
    for name, desc in entries.items():
        team_obj = Team(name=name, description=desc)
        team_obj.save

def populate_role(apps, schemaeditor):
    entries = {
        "developer" :"can change status of issue",
        "scrum master" :"can change assignee",
        "product owner" :"can create issues",

    }

    Role = apps.get_model("accounts", "Role")
    for name, desc in entries.items():
        role_obj =Role(name=name, description=desc)
        role_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_teams),

    ]
